services:
  - type: worker
    name: mexc-ping-test
    env: python
    region: singapore   # Alternativ: frankfurt, oregon, ohio
    plan: free
    buildCommand: ""
    startCommand: "python ping_mexc.py"
